<!-- Made by Andrew -->
<?php require ("Views/template/header.phtml");?>
<div style="text-align: center;">
    <img src="/images/TilePlan-Flooring-Survey-Team.webp" alt="survey team image" style="max-width: 520px; margin-top: 20px;">
    <a><pre>
Short on time? Review your options and receive an accurate
quote within minutes. The result is a fast, efficient and reliable
way to prepare your project with clarity and confidence.
        </pre></a>
</div>
<?php require ("Views/template/footer.phtml");?>
